spring:
  datasource:
    # URL will be overridden if we use Testcontainers, but we set a default H2 database in memory for simple unit tests
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    enabled: false

jwt:
  secret: stockflow_very_secure_secret_key_that_is_at_least_256_bits_long_abcdefg

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    com.stockflow.inventory: INFO
